### PR TITLE
Team fix

### PR DESCRIPTION
**Pull request by Razor421**
latin fixes on:
Contacts 
Team 

short minor fixes on:
home page
projects page

### CODE REVIEW

**Comment by StoneMcYT** [comment]
https://github.com/ASEAN-Build-The-Earth/AseanBTE-Website/issues/93

Related To

**Comment by tintinkung** [comment]
this pull request have no changes with team page tho, and your branch is outdated alot

**Comment by StoneMcYT** [comment]
> 
> 
> this pull request have no changes with team page tho, and your branch is outdated alot

Hmm alot of grammer errors when editing files removed alot pf PfP icos

**Comment by Razor421** [comment]
> 
> 
> this pull request have no changes with team page tho, and your branch is outdated alot

I mean I just created a branch...

**Comment by tintinkung** [comment]
> I mean I just created a branch...

ohh... I thought this is ready to review. 
next time make pull request when ur branch is atleast 80% done ;-; or mark it as draft pr

**Comment by Razor421** [comment]
made a new one and it had a day for the branch to be done and wym no changes with team page?

**Comment by tintinkung** [comment]
> wym no changes with team page?

currently: 
image

**Pull request closed without merging**
