### PR TITLE
License Adition.

### PR DESCRIPTION
**Pull request by StoneMcYT**
Just gonna keep major changes on forks to reduce clashes.

### CODE REVIEW

**Comment by Kira272921** [comment]
🤔 Add the entire license text in `LICENSE` file

**Comment by StoneMcYT** [comment]
> 🤔 Add the entire license text in `LICENSE` file

I did that in 
https://github.com/ASEAN-Build-The-Earth/AseanBTE-Website/pull/103/commits/bfad5f6376a38e23882e3958aa072d91adeedde5

**Comment by Kira272921** [comment]
> > 🤔 Add the entire license text in `LICENSE` file
> 
> I did that in [bfad5f6](https://github.com/ASEAN-Build-The-Earth/AseanBTE-Website/commit/bfad5f6376a38e23882e3958aa072d91adeedde5)

😂 It's 2022 not 2021

**Comment by StoneMcYT** [comment]
> > > 🤔 Add the entire license text in `LICENSE` file
> > 
> > 
> > I did that in [bfad5f6](https://github.com/ASEAN-Build-The-Earth/AseanBTE-Website/commit/bfad5f6376a38e23882e3958aa072d91adeedde5)
> 
> 😂 It's 2022 not 2021

Nope when licensing you write in the data the item was created and our first commit was around October 2021

**Pull request merged**
