### PR TITLE
Fade off on scroll effect

### PR DESCRIPTION
**Pull request by Kira272921**
https://user-images.githubusercontent.com/90365542/139819030-ff8eee37-319e-42db-8275-62835bd27579.mp4

### CODE REVIEW

**Comment by tintinkung** [comment]
hm
i tried playing with your conflict and kinda fixed it 
image

idk you want to update it urself or what, so imma let it be a choice if you can solve the conflict

**Comment by Kira272921** [comment]
> hm i tried playing with your conflict and kinda fixed it image
> 
> idk you want to update it urself or what, so imma let it be a choice if you can't solve the conflict

oh wow, thanks 😅 umm.. could you update it ?

**Comment by tintinkung** [comment]
> oh wow, thanks 😅 umm.. could you update it ?

aright it is now up-to-date

**Comment by Kira272921** [comment]
> > oh wow, thanks 😅 umm.. could you update it ?
> 
> aright it is now up-to-date

yay! 🚀 thanks!!

**Pull request merged**
