### PR TITLE
FAQ page and other minor fixes

### PR DESCRIPTION
**Pull request by Kira272921**
Changed the FAQ page, as the design was had been used over two times
Minor fixes include:
- Adding the meta tags to every page
- Few typography fixes in image slideshow on the home page

I am not confident about the responsiveness of the FAQ page, I would be great if someone actually tests it out

### CODE REVIEW

**Review by tintinkung — APPROVED** [review]
## :heavy_check_mark: Approved
everything looks good nice template

**Review by StoneMcYT — APPROVED** [review]
Looks good!

**Comment by tintinkung** [comment]
## 🔒 ok merge-able check

**Review by tintinkung — CHANGES_REQUESTED** [review]
alright the contact-us update should be make in new branch. I dont want user-interaction in main branch yet. we might have more UI changes on the page and updating it with the smptjs might be confusing

I can merge if you shift the contact-us update away 🙇

**Comment by tintinkung** [comment]
thenks

**Review by tintinkung — APPROVED** [review]

**Pull request merged**
