### PR TITLE
Trial run of 404 page

### PR DESCRIPTION
**Pull request by Razor421**
just did a 404 page using a tutorial, 
just a test to see whats wrong
so i can better make it next time

[https://github.com/Razor421/AseanBTE-Website/commit/799f31264b3e2156ff834a1b435f74aebed265c7](url)
thats the code, think github desktop commit

### CODE REVIEW

**Comment by Razor421** [comment]
also stone, kira says u shud link it with netlify

**Comment by tintinkung** [comment]
this is interesting but i wonder does it actually work? im not pro with theses stuff
can you test it and make the 404 page appear somehow

**Comment by Razor421** [comment]
yes. testing is on its way.

**Comment by tintinkung** [comment]
@Razor421 um id this still active

**Comment by tintinkung** [comment]
closed: `no response and inactive`
> 22/12/2021

**Pull request closed without merging**
