### PR TITLE
Added FAQ page and update all indexs pages

### PR DESCRIPTION
**Pull request by pratap360**

### CODE REVIEW

**Review by StoneMcYT — APPROVED** [review]
Looks good!

**Comment by pratap360** [comment]
thank you

**Review by tintinkung — CHANGES_REQUESTED** [review]
<details><summary>bro this is too obivious</summary>

image
</details>

- alot of html tag dont even completed
- all html is poorly organize
- you dont even tried to change the font at all. 
- now all you do is
  1. copy our current work
  2. go to bte website 
  3. press inspect 
  4. crtl c, v to the file
  5. apply the pr then pretend to be cool
  
I knows you are farming for hacktoberfest but you cant just copy a html from someone's website frontend and paste it here without knowing anything. I'm disappointed

I do appreciate some work that you tried mixing thing up together but it just doesnt feels right

**Comment by pratap360** [comment]
I know i'm not the best but yes i can do and gave my best
as you told all the 4 point but yes **i didn't feels cool** because I take the time to under the all the code form the inspect and view source element it and to this repo also, 
 by the way  so what should i change ? tell me i will do that

**Comment by tintinkung** [comment]
ah sorry maybe i've gone too far
> so what should i change ? tell me i will do that

you could start from re-organizing your work and fix the 4 point i've said

**Comment by pratap360** [comment]
no problem brother

**Comment by pratap360** [comment]
image

as you told the 4th point according to it this the simple one is this acceptable or not ?

**Comment by tintinkung** [comment]
> as you told the 4th point according to it this the simple one is this acceptable or not ?

Im not sure what but if you want me to review from that picture, No. 
- it stills look the same as the original website you copied. what if I accept this and someone found out we just copy other website's html? If you are not sure what to put in text box. you can also put tempolary sentence like the "Lorem ipsum, dolor" we put in contact-us page and we'll help out how your work gonna looks like. 

I accept all size of work as long as it shows the propose of that work.
In my opinion, i just dont appreciate this type of works. 
you are lucky this website is in prototype state. you'll get absolute destroy if you do this to more serious open source project.

**Comment by tintinkung** [comment]
## 🔐 Closed: Expired
can be open again if no-longer inactive

**Pull request closed without merging**
