### PR TITLE
Rewritten FAQ from latin to english.

### PR DESCRIPTION
**Pull request by S4ge-Rites**

### CODE REVIEW

**Comment by S4ge-Rites** [comment]
Can someone check the PR?

**Review by StoneMcYT — COMMENTED** [review]
Did you just copy paste stuff?

**Comment by tintinkung** [comment]
> Did you just copy paste stuff? 

i mean it works but idk

**Comment by StoneMcYT** [comment]
> 
> 
> > Did you just copy paste stuff?
> 
> i mean it works but idk

Eh the code is alot like this. the css is in html file somehow
image

**Comment by tintinkung** [comment]
> Eh the code is alot like this. the css is in html file somehow 

rite's code is completely fine nothing bad with that

**Review by tintinkung — COMMENTED** [review]
5 / 10
> code: 10/10
> Innovation 0/10

we will have 3 page of a SAME template, isnt that seems too duplicate

**Comment by Sergestra** [comment]
I agree with @StoneMcYT about inline styling -

Since the start of my collaboration on this project I noticed inline-styling being implemented in the html files. Would be great if all inline-styling was removed from the html files and added to their corresponding css files, it makes it easier to update and add changes to css, not to mention inline-styling is not a great practice.

Makes it easier for other contributors to find and edit the css.

Was having trouble updating font sizes due to this, had to remove the inline styling from the projects html and added it to the css.

I also agree with @tintinkung about the rest of the code not having any issues, though the design looks the same we can update it easily while keeping the layout.

**Comment by StoneMcYT** [comment]
I think re

> 
> 
> 5 / 10
> 
> > code: 10/10
> > Innovation 0/10
> 
> we will have 3 page of a SAME template, isnt that seems too duplicate

I totally agree with this. so i was thinking that we could move to something like his?
image

**Comment by Kira272921** [comment]
> I think re
> 
> > 5 / 10
> > > code: 10/10
> > > Innovation 0/10
> > 
> > 
> > we will have 3 page of a SAME template, isnt that seems too duplicate
> 
> I totally agree with this. so i was thinking that we could move to something like his? image
> 
> Image from https://htmlcss3tutorials.com/faq-page-with-show-and-hide-questions-and-answers/

@StoneMcYT Can i work on this ?

**Comment by StoneMcYT** [comment]
> 
> 
> > I think re
> > > 5 / 10
> > > > code: 10/10
> > > > Innovation 0/10
> > > 
> > > 
> > > we will have 3 page of a SAME template, isnt that seems too duplicate
> > 
> > 
> > I totally agree with this. so i was thinking that we could move to something like his? image
> > Image from https://htmlcss3tutorials.com/faq-page-with-show-and-hide-questions-and-answers/
> 
> @StoneMcYT Can i work on this ?

Assigned

**Comment by Kira272921** [comment]
#80 Made a pull request 
Need review about the responsiveness of the FAQ page

**Comment by S4ge-Rites** [comment]
Uhh sorry about the whole entire copypasting Faq thing i rewritten into my own words pls check the PR one more time.

**Comment by tintinkung** [comment]
alright @S4ge-Rites 
your work is now moved to pr #85 and squashed together with kira and razor's works to avoid anymore conflict

thenks

**Comment by tintinkung** [comment]
## 🔏 Closed: Content Transferred

**Pull request closed without merging**
